name : Continuous Integration Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'checkout code'
    uses : action/checkout@v1
    
    - name:'Set up JDK 1.8'
    uses: action/setup-java@v1
    with:
      java-version: 1.8
    
    - name: 'build'
    run: mvn -B package -file pom.xml
